### ISSUE TITLE
Landing browser

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#14]
Se scelgo di aprire un link all'articolo su landing (nel browser) la pagina dovrebbe mandare un alert chiedendo se voglio aprire l'app o continuare a leggere su browser (come su iOs)... invece ora mi porta direttamente all'App

**Comment by gianlucatursi** [comment]
In realtà questa è la vera funzionalità del Deep Link che, senza chiedere, automaticamente capisce che l'articolo fa parte dell'app e se è installata la apre. Il problema è su iOS e non su Android. 
Abbiamo inviato qualche settimana fa una mail chiedendo di impostare il DNS sui nostri service questo perchè io devo mandare in submission ad Apple il fatto che (esempio) `article.communitysmart.it/:id ` è l'url di un deep link e che apre l'app. Senza questa informazione non è possibile completare il Deep link su iOS e quindi, per mostravi che funziona, abbiamo messo un piccolo script sulla pagina.
