### ISSUE TITLE
Comunicazione consumo dati per i video

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#15]
Alcune volte, aprendo un video su connessione Dati Cellulare, arriva un alert che ti avvisa del fatto che consumerai traffico dati... questo alert dovrebbe essere in italiano.
**Edit**: possibilmente eliminare completamente questo alert

**Comment by Community-Tech** [comment]
L'alert è in inglese anche se il device ha la langua in Italiano

![whatsapp image 2018-01-11 at 21 26 32](https://user-images.githubusercontent.com/33541658/34845759-49516fb8-f716-11e7-8127-cb46bee1598a.jpeg)

**Comment by digitalx-dev** [comment]
https://github.com/Community-Tech/ios/issues/17
