### ISSUE TITLE
Aggiornamento Feed notizie, canali

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#19]
Aggiornare i feed tramite scroll verso il basso (come iOs)

**Comment by digitalx-dev** [comment]
Al mio collega di Android serve "Change" per capire che è una modifica di quello che ha già fatto. Il "Change" che pensate voi lo segnaliamo come "enhancement"

**Comment by Community-Tech** [comment]
Grazie per il chiarimento
