### ISSUE TITLE
Lightbox immagini non funziona + Icona chiudi

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#26]
Se apro l'articolo e faccio tap sull'immagine per ingrandirla non si apre l'immagine.. rimane fisso il loader (solo su alcune immagini, ad esempio nessuna del canale Savigliano News).
Inoltre manca un pulsante chiudi (X) della lightbox... devo per forza utilizzare il tasto Back

**Comment by digitalx-dev** [comment]
Il problema delle immagini che non si caricavano viene fuori quando si cerca di aprire una sola immagine (risolto). Su Android a differenza di iOS, si tende ad utilizzare molto il tasto Back del telefono, sopratutto se si apre una galleria di immagini. Facebook per esempio, se apri un'immagine non ti propone nessuna icona per tornare indietro.
