### ISSUE TITLE
Breaking News

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#30]
quando ricevo la notifica di "Breaking news" e la apro... non trovo la notizia in breaking news... l'app si apre sull'ultima edizione disponibile in prima pagina.
se tap su Breaking news... mi aspetto breaking news

**Comment by digitalx-dev** [comment]
Dobbiamo ancora aggiornarvi l'app con le breaking news (anche iOS). Le riceve ma non le gestisce.
