### ISSUE TITLE
Condividi e commenta... senza essere loggato

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#32]
Ho appena condiviso una notizia dall'app senza essere loggato!
Ho anche commentato, ma sulla dashboard non risulto loggato... la app da quando ho scaricato l'aggiornamento non mi ha più chiesto di loggarmi!

**Comment by digitalx-dev** [comment]
Grazie della segnalazione. 
Ho aggiunto ulteriori controlli per forzare il redirect alla login in caso l'utente voglia commentare, rispondere al commento, salvare un articolo oppure condividere. Ho aggiornato l'applicazione alla versione 1.0.0 sul PlayStore. E' consigliato disinstallare l'attuale applicazione e installarla nuovamente. Questo perchè, come richiesto, abbiamo effettuato la pulizia totale del DB ed alcuni dati potrebbero essere spuri.  (Questo per tutti gli attuali tester, tutti gli account creati su community non esistono più) 
Quando l'applicazione si aggiorna e l'utente era già loggato, non chiede più di loggarsi ma effettua un "auto-login".
