### ISSUE TITLE
Aggiornamento Android

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#33]
Ragazzi che ci sia l'aggiornamento della app su android dei nostri tester non lo sa nessuno... come possiamo comunicare questa cosa? e nel futuro quando aggiorniamo l'app come funzionerà? grazie.

**Comment by digitalx-dev** [comment]
In fase di testing iOS invia la mail alla nuova versione, Android no. Non cè modo di notificare un update dell'app di test se non inviare una mail.
