### ISSUE TITLE
logout... non funziona

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#34]
faccio la procedura di logout e quando rientro il mio profilo è caricato sulla piattaforma esattamente come prima del logout... non funziona!!!

**Comment by digitalx-dev** [comment]
Ciao, fai riferimento a questa risposta: https://github.com/Community-Tech/android/issues/32

**Comment by Community-Tech** [comment]
ho disinstallato l'app dal mio device e l'ho rinstallata da store... è corretto che il mio profilo fosse già caricato e che quindi non mi abbia richiesto nessun login??? grazie

**Comment by digitalx-dev** [comment]
Ciao, 
Cosa intendi con "il tuo profilo era già caricato"... Hai scaricato l'applicazione dallo store, avendola disinstallata, sei andato nella schermata "di più" e hai visto la tab "Profilo"?
Se invece con "sono loggato" intendi che puoi condividere (perchè dovrebbe darti errore se provi a commentare), ti prego di fare riferimento alla risposta dell'issue #32

**Comment by Community-Tech** [comment]
intendo che dopo aver installato la app da store sono andato su di+/profilo e avevo i miei dati caricati... ripeto, non ho fatto un aggiornamento, ma ho disinstallato la app dal mio device e l'ho riscaricata da store.

**Comment by digitalx-dev** [comment]
Grazie del chiarimento...
E' un comportamento molto strano perchè quando disinstalli l'applicazione, il sistema operativo cancella anche tutti i dati correlati all'applicazione... Non mi so spiegare come mai questo non si avvenuto nel tuo caso... Che telefono stai utilizzando?

Ho fatto la tua stessa procedura e non mi trovo l'account loggato dopo la nuova installazione a seguito della disinstallazione dal PlayStore.

**Comment by Community-Tech** [comment]
Ok, ho appena rifatto l'operazione e ticonfermo che non appena installata l'app ha il mio profilo caricato... ti mando una mail su support@digitalx.it con lo screenshot
Intanto ti dico che il telefono che sto usando è: Samsung Galaxy S6 - modello SM-G920F con sistema operativo Android 7.0 ... se ti serve altro chiedi...
