### ISSUE TITLE
sezione di+

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#36]
Aprendo l'app nella sezione "Di più" i seguenti link portano a "404 Article not found":
- Domande frequenti
- Richiedi assistenza
- Come fare pubblicità
- App Commmunity Smart
- Privacy e termini di utilizzo

**Comment by digitalx-dev** [comment]
Da chiedere a Giorgio di attivare le pagine sul sito web di community smart secondo gli indirizzi forniti a gennaio. Creato nuovo TAG della gestione issue, contenente community smart per indicare le problematiche non dipenendenti da DigitalX
