### ISSUE TITLE
Problemi sul video

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#41]
Un utente (dispositivo huawei) ci ha segnalato che i video non partono e dopo un pò di attesa appare un messaggio in cinese
![whatsapp image 2018-02-12 at 23 45 35](https://user-images.githubusercontent.com/33541658/36124155-4be570e2-104f-11e8-9d1f-ad59780872cb.jpeg)

**Comment by digitalx-dev** [comment]
Problema rilevato e segnalato al centro di assistenza Vimeo per risoluzione,
