### ISSUE TITLE
Notifiche su dispositivo Samsung

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#46]
Ci hanno segnalato che su un dispositivo Samsung S5 - Android 6.0.1, facendo click sulla notifica "Leggi l'edizione del giorno" non viene aperta l'applicazione ma semplicemente viene visualizzato il desktop

**Comment by digitalx-dev** [comment]
Purtroppo non ci è possibile intervenire nella logica del singolo dispositivo. Le spiegazioni più plausibili potrebbero essere almeno 3:

- non corretto utilizzo della schermata di notifiche
- bug di sistema per le notifiche

Per risolvere il problema, potrebbe essere necessario effettuare delle prove in più giorni e soprattutto vedere cosa succede su una notifica mandata da un app scaricata dallo store sempre su quel dispositivo.

**Comment by Community-Tech** [comment]
ok, grazie per i consigli
