### ISSUE TITLE
Logout non funzionante

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#47]
Se faccio esci dal profilo, l'app torna alla prima pagina ma risulto sempre loggato (Samsung S6 - Android 7.0)

**Comment by digitalx-dev** [comment]
La problematica è già stata segnalata ed è stato inviato ad Andrea una demo personale per la possibile soluzione per le tipologie di dispositivo a cui però non è stata fornita alcuna risposta. Attendiamo risposta del test del apk per rilasciare l'aggiornamento.
