### ISSUE TITLE
App Test: numeri utili - ordinamento sbagliato

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#69]
L'ordinamento di numeri utili continua ad essere sbagliato.
Numeri utili, ordine inverso
#55 opened on 21 Feb by giosh

**Comment by digitalx-dev** [comment]
Non è ancora stato rilasciato l'aggiornamento che risolve questo problema e https://github.com/Community-Tech/android/issues/68 

Essendo dispendioso aggiornare tutte le app stiamo "accumulando" i bug per risolverli tutti insieme e fare un unico rilascio

**Comment by Community-Tech** [comment]
Questo è però un argomento ed una modalità operativa rischiosa. Con queste premesse abbiamo trascinato una grande quantità di problemi a causa di averli sempre posticipati.
Non accumuliamo troppo!!!
Grazie.
