### ISSUE TITLE
Canali preferiti sulla barra dei Canali

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#7]
Sulla barra dei canali dovrebbero apparire solo quelli che seguo giusto?
Ora appaiono tutti comunque.

**Comment by digitalx-dev** [comment]
Si era scelto insieme di avere tutti i canali sulla barra e, in più, la tab "Seguiti" nel caso in cui si segua almeno un canale. Questo perchè tutti gli utenti che non vogliono (o non sono ancora) iscritti avrebbero una sezione completamente vuota.
