### ISSUE TITLE
Notifica Automatica delle 8:00 "Edizione del giorno"

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#75]
Casistica su SAVIGLIANO SMART (produzione):
Problema riscontrato: se durante la notte spengo il telefono e lo riaccendo dopo le 8:00 (orario di uscita della notifica), la notifica non arriva più. Su iOS in pari condizioni la notifica arriva.

**Comment by digitalx-dev** [comment]
E' un comportamento del sistema operativo. Su iOS, che sia spento o accesso, arrivano. Su Android se la notifica viene inviata quando un utente ha il telefono spento Google non la rispedisce.
