### ISSUE TITLE
Menu Archivio Edizioni

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/android#9]
L'icona del menu archivio edizioni non si capisce senza label.
La tendina dovrebbe avere un titolo.
La parola Custom deve cambiare in Personalizza

**Comment by digitalx-dev** [comment]
Modificato la parola in Personalizza. Per la label c'è il problema dello spazio su dispositivi più piccoli se viene sempre mostrata, se si tiene premuto sull'icona la label comunque appare per far capire che funzionalità ha quel determinato bottone.
